name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      # retrieve your distributions here
      - uses: actions/checkout@v1
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
